# The Lattice constraint file for a design on a board: where each port sits, how
# its buffer is configured, what every clock runs at, and the timing exceptions
# the design declares. Emitted with the Verilog, from the same declarations, so
# the two agree by construction.

Base.write(io::IO, T::Type{<:QuartzModule}, f::LPF) = (buf = IOBuffer(); _lpf(buf, T, f.board); write(io, take!(buf)))

function _lpf(io::IO, T::Type{<:QuartzModule}, b::Board)
  bad = problems(b, T)
  isempty(bad) ||
    error("$(b.name) and $(nameof(T)) do not agree:\n  " * join(bad, "\n  "))
  println(io, "// generated by QuartzHDL for $(nameof(T)) on $(b.name)",
          isempty(b.device) ? "" : " ($(b.device))")
  isempty(b.raw) || println(io, strip(b.raw))
  for (p, i, s) in _sites(b)
    println(io, "LOCATE COMP \"$(_bitname(T, p, i))\" SITE \"$s\" ;")
  end
  for (p, i, _) in _sites(b)
    println(io, "IOBUF PORT \"$(_bitname(T, p, i))\" $(_iobufopts(b, p, i - 1));")
  end
  for net in _checkedprimary(T)
    println(io, "USE PRIMARY NET \"$(_pinname(T, net))\" ;")
  end
  rates = clockrates(T, b)
  for net in sort(collect(keys(rates)))
    println(io, "FREQUENCY NET \"$(_pinname(T, net))\" $(_mhz(rates[net])) MHz ;")
  end
  for M in _allmodules(T), m in _allmulticycles(M)
    println(io, _multicyclestr(T, M, m))
  end
  nothing
end

# every located bit of a board's pins: the pin, the bit's index, and its site
_sites(b::Board) = ((p, i, s) for p in b.pins for (i, s) in enumerate(p.sites) if s !== nothing)
