# The Lattice constraint file for a design on a board: where each port sits, how
# its buffer is configured, the rate of every clock the logic runs on, and the
# timing exceptions the design declares. Emitted with the Verilog, from the same
# declarations, so the two agree by construction.

Base.write(io::IO, T::Type{<:QuartzModule}, f::LPF) =
  (buf = IOBuffer(); _lpf(buf, T, f.board, f.overconstrain); write(io, take!(buf)))

function _lpf(io::IO, T::Type{<:QuartzModule}, b::Board, overconstrain::Float64)
  bad = problems(b, T)
  isempty(bad) ||
    error("$(b.name) and $(nameof(T)) do not agree:\n  " * join(bad, "\n  "))
  println(io, "// generated by QuartzHDL for $(nameof(T)) on $(b.name)",
          isempty(b.device) ? "" : " ($(b.device))")
  overconstrain == 1 ||
    println(io, "// clocks are constrained at $overconstrain times their rates, to measure the room a build has")
  isempty(b.raw) || println(io, strip(b.raw))
  for (p, i, s) in _sites(b)
    println(io, "LOCATE COMP \"$(_bitname(T, p, i))\" SITE \"$s\" ;")
  end
  for (p, i, _) in _sites(b)
    println(io, "IOBUF PORT \"$(_bitname(T, p, i))\" $(_iobufopts(b, p, i - 1));")
  end
  for net in _checkedprimary(T)
    println(io, "USE PRIMARY NET \"$(_primarynet(T, net))\" ;")
  end
  rates = clockrates(T, b)
  used = _clocks(T)
  for net in sort(collect(keys(rates)))
    net in used || continue
    kind = _onpin(T, net) ? "PORT" : "NET"
    println(io, "FREQUENCY $kind \"$(_pinname(T, net))\" $(_mhz(rates[net] * rationalize(overconstrain))) MHz ;")
  end
  for M in _allmodules(T), m in _allmulticycles(M)
    println(io, _multicyclestr(T, M, m))
  end
  nothing
end

# Synthesis puts a buffer behind a clock pin and names the net after it `<port>_c`,
# so a net-level constraint on the port's own name matches nothing and is dropped.
# FREQUENCY can name the port instead; USE PRIMARY names only nets, so it takes the
# buffered name, which is Synplify's, the synthesiser the Diamond workspace selects.
_onpin(T::Type, net::Symbol) = net in _clocksof(T)
_primarynet(T::Type, net::Symbol) = string(_pinname(T, net), _onpin(T, net) ? "_c" : "")

# every located bit of a board's pins: the pin, the bit's index, and its site
_sites(b::Board) = ((p, i, s) for p in b.pins for (i, s) in enumerate(p.sites) if s !== nothing)

# The same clocks and exceptions as Synplify reads them. Map and place-and-route
# read the LPF; synthesis reads an .fdc, and without one it times every path
# against a default clock and knows nothing of the multicycle paths, so the path
# it works hardest on is one the design allows many cycles for. Synplify spells
# names its own way: hierarchy with a dot, the bits of a register as `[*]`, and a
# clock a vendor's netlist makes by the pin that drives it, `pll1.CLKOP`.
function _fdc(io::IO, T::Type{<:QuartzModule}, b::Board, overconstrain::Float64)
  println(io, "# generated by QuartzHDL for $(nameof(T)) on $(b.name); the same clocks and exceptions as the LPF")
  rates = clockrates(T, b)
  used = _clocks(T)
  made = _clocksmade(T)
  for net in sort(collect(keys(rates)))
    net in used || continue
    period = 1e9 / float(rates[net] * rationalize(overconstrain))
    where = _onpin(T, net) ? "get_ports" : "get_nets"
    println(io, "create_clock -name {$(_pinname(T, net))} -period $(round(period; digits=3)) [$where {$(get(made, net, _pinname(T, net)))}]")
  end
  for M in _allmodules(T), m in _allmulticycles(M)
    println(io, _fdcmulticyclestr(T, M, m))
  end
  nothing
end

# the clock nets of the top module that a black box with a netlist of its own
# makes, by the name Synplify has for them: the instance and the pin, which is a
# net inside the netlist. A primitive's output net keeps the design's name.
function _clocksmade(T::Type)
  made = Dict{Symbol,String}()
  for (f, FT) in zip(fieldnames(T), fieldtypes(T))
    isblackbox(FT) && !blackbox(FT).primitive || continue
    binds = _clockbind(T, f)
    for p in blackbox(FT).ports
      p.dir === :clockout || continue
      net = _boundnet(binds, p.name)
      net === nothing || (made[net] = "$f.$(p.vname)")
    end
  end
  made
end

function _fdcmulticyclestr(T::Type, M::Type, m::MultiCycle)
  fields = _fieldinfo(M)
  cell(path, f) = (i = _finfo(fields, f); _fdcprefix(path) * string(f) * (i !== nothing && i.width == 1 ? "" : "[*]"))
  join(("set_multicycle_path $(m.cycles) -from [get_cells {$(cell(path, m.from))}] -to [get_cells {$(cell(path, m.to))}]"
        for path in _instancepaths(T, M)), "\n")
end

_fdcprefix(path) = isempty(path) ? "" : join(path, ".") * "."
