# The Quartus side of a board: the settings file, which says where each port sits
# and how its buffer is configured, and the timing constraints, which say how fast
# every clock runs and which paths may take more than a cycle. Quartus keeps the two
# apart -- a rate is not a setting -- so they are two formats, written from the same
# declarations as the Verilog, so the three agree by construction. A board's default
# I/O standard is also the device's: without it, Quartus supplies the banks that no
# port lands in at 2.5 V, and the configuration pins end up across two voltages.

# The family a part belongs to, by how its number begins; Quartus wants the family
# named beside the device. A part that begins with none of these is not one
# Quartus builds for.
const QUARTUS_FAMILIES = ["10M" => "MAX 10", "10CL" => "Cyclone 10 LP", "5C" => "Cyclone V",
                          "EP4CE" => "Cyclone IV E", "EP4CGX" => "Cyclone IV GX"]

# an I/O standard as a board writes it, and as Quartus spells it
const QUARTUS_IOSTANDARDS = Dict(:LVCMOS33 => "3.3-V LVCMOS", :LVTTL33 => "3.3-V LVTTL", :LVCMOS25 => "2.5 V",
                                 :LVCMOS18 => "1.8 V", :LVCMOS15 => "1.5 V", :LVCMOS12 => "1.2 V",
                                 :LVDS => "LVDS")

Base.write(io::IO, T::Type{<:QuartzModule}, f::QSF) =
  (buf = IOBuffer(); _qsf(buf, T, f.board); write(io, take!(buf)))
Base.write(io::IO, T::Type{<:QuartzModule}, f::SDC) =
  (buf = IOBuffer(); _sdc(buf, T, f.board, f.overconstrain); write(io, take!(buf)))

function _qsf(io::IO, T::Type{<:QuartzModule}, b::Board)
  family = _checkedquartus(b, T)
  println(io, "# generated by QuartzHDL for $(nameof(T)) on $(b.name) ($(b.device))")
  println(io, "set_global_assignment -name FAMILY \"$family\"")
  println(io, "set_global_assignment -name DEVICE $(b.device)")
  io_default = get(b.defaults, :io, nothing)
  io_default === nothing ||
    println(io, "set_global_assignment -name STRATIX_DEVICE_IO_STANDARD \"$(_quartusio(io_default))\"")
  isempty(b.raw) || println(io, strip(b.raw))
  for (p, i, s) in _sites(b)
    println(io, "set_location_assignment PIN_$s -to $(_bitname(T, p, i))")
  end
  for (p, i, _) in _sites(b), a in _qsfassignments(b, p, i - 1)
    println(io, "set_instance_assignment -name $a -to $(_bitname(T, p, i))")
  end
  for net in _checkedprimary(T)
    println(io, "set_instance_assignment -name GLOBAL_SIGNAL \"GLOBAL CLOCK\" -to $(_pinname(T, net))")
  end
  nothing
end

function _sdc(io::IO, T::Type{<:QuartzModule}, b::Board, overconstrain::Float64)
  _checkedquartus(b, T)
  println(io, "# generated by QuartzHDL for $(nameof(T)) on $(b.name); the clocks and timing exceptions the design declares")
  overconstrain == 1 ||
    println(io, "# clocks are constrained at $overconstrain times their rates, to measure the room a build has")
  rates = clockrates(T, b)
  used = _clocks(T)
  made = _clocksmade(T)
  for net in sort(collect(keys(rates)))
    net in used || continue
    period = 1e9 / float(rates[net] * rationalize(overconstrain))
    name = _pinname(T, net)
    target = haskey(made, net) ? "[get_pins {$(replace(made[net], "." => "|"))}]" :
             _onpin(T, net) ? "[get_ports {$name}]" : "[get_nets {$name}]"
    println(io, "create_clock -name {$name} -period $(round(period; digits=3)) $target")
  end
  println(io, "derive_clock_uncertainty")
  for M in _allmodules(T), m in _allmulticycles(M)
    println(io, _sdcmulticyclestr(T, M, m))
  end
  nothing
end

### helpers

_quartusfamily(device::AbstractString) =
  (i = findfirst(((prefix, _),) -> startswith(uppercase(device), prefix), QUARTUS_FAMILIES);
   i === nothing ? nothing : QUARTUS_FAMILIES[i].second)

# the board's family, once the board is one Quartus builds for and agrees with the design
function _checkedquartus(b::Board, T::Type)
  family = _quartusfamily(b.device)
  family === nothing &&
    error("$(b.name) names $(repr(b.device)), which is not a part Quartus builds for; the families known are " *
          join(last.(QUARTUS_FAMILIES), ", "))
  bad = problems(b, T)
  isempty(bad) || error("$(b.name) and $(nameof(T)) do not agree:\n  " * join(bad, "\n  "))
  family
end

# A pull is written even when it is off, since a buffer's pull is worth stating; an
# explicit `pull = nothing` leaves it to the tool. MAX 10 and its kin have a weak
# pull-up only, so a pull-down has to be a resistor on the board.
function _qsfassignments(b::Board, p::PinBinding, bit::Int)
  out = String[]
  io = _bitattr(b, p, :io, bit, nothing)
  io === nothing || push!(out, "IO_STANDARD \"$(_quartusio(io))\"")
  pull = _bitattr(b, p, :pull, bit, :none)
  pull === :down &&
    error("$(portof(p)) is pulled down on $(b.name), and Quartus has no weak pull-down; a resistor on the board is ext_pull")
  pull === nothing || push!(out, "WEAK_PULL_UP_RESISTOR " * (pull === :up ? "ON" : "OFF"))
  dr = _bitattr(b, p, :drive, bit, nothing)
  dr === nothing || push!(out, "CURRENT_STRENGTH_NEW $(dr)MA")
  out
end

_quartusio(io::AbstractString) = String(io)
_quartusio(io::Symbol) = get(QUARTUS_IOSTANDARDS, io) do
  error("no Quartus spelling is known for the I/O standard :$io; the standards known are " *
        join(sort(string.(keys(QUARTUS_IOSTANDARDS))), ", ") * ", or give Quartus's own spelling as a string")
end

# Quartus names a register by its instance path with `|` between the levels and the
# bit index on the end, so a pattern is the path and a `*`; a setup exception of N
# cycles pairs with a hold exception of N-1, which keeps the hold check where the
# default has it. _mkmulticycle refuses a design where another register could
# complete the pattern.
function _sdcmulticyclestr(T::Type, M::Type, m::MultiCycle)
  join((join(("set_multicycle_path -$kind $n -from [get_registers {$p$(m.from)*}] -to [get_registers {$p$(m.to)*}]"
              for (kind, n) in (("setup", m.cycles), ("hold", m.cycles - 1))), "\n")
        for p in (_sdcprefix(path) for path in _instancepaths(T, M))), "\n")
end

_sdcprefix(path) = isempty(path) ? "" : join(path, "|") * "|"
