# A vendor part's netlist usually cannot be simulated without the vendor's primitive
# library, so a behavioural stand-in takes its place. Generating it from the same
# clockout declarations the simulator uses is the point: the two models of the clock
# tree are then one description, and cannot drift apart the way two hand-written ones
# can.

"""
    simmodel(io, T; scale=Dict{Symbol,Int}())
    simmodel(path, T; scale=Dict{Symbol,Int}())

Write a behavioural Verilog stand-in for the black box `T`, built from its
`@clockout` declarations: a module of the same name and ports whose clock
outputs divide, phase and gate exactly as the simulator's model of `T` does.
Its data outputs are tied to zero. `scale` overrides the divider of a clock by
name, to cover many periods of a slow domain in a few thousand cycles.

```julia
simmodel("pll.v", PLL; scale=Dict(:clk_slow => 4))
```
"""
function simmodel(io::IO, T::Type; scale=Dict{Symbol,Int}())
  divs = _asclockscale(scale)
  bb = blackbox(T)
  bb === nothing && error("$(nameof(T)) is not a black box")
  isempty(bb.tree) && error("$(bb.verilogname) declares no clock tree")
  e = Emitter()
  out = e.io
  println(out, "// generated by QuartzHDL from the clockout declarations of $(bb.verilogname)")
  println(out, "`timescale 1ns/1ns")
  println(out, "module $(bb.verilogname) (")
  println(out, join(("  " * d for d in _simdecls(bb)), ",\n"))
  println(out, ");\n")
  enables = _simenables(e, T, bb)
  for (i, c) in enumerate(bb.tree)
    get(divs, c.name, c.divide) > 1 && println(out, "  reg [31:0] n$(i)_$(_vport(bb, c.name)) = 32'd0;")
  end
  println(out, "  initial begin")
  for c in unique(x.name for x in bb.tree)
    println(out, "    $(_vport(bb, c)) = 1'b0;")
  end
  println(out, "  end\n")
  _emit_wires!(e, sort(collect(values(_simnodes(enables))); by=n -> n.id))
  # a clock that divides by one is its source under another name, low half included,
  # so a design that samples it as data reads the level the source has
  for (i, c) in enumerate(bb.tree)
    (c.from === nothing || get(divs, c.name, c.divide) != 1) && continue
    en = get(enables, i, nothing)
    println(out, "  always @(negedge $(_vport(bb, c.from)))",
            en === nothing ? "" : " if ($(_ref(e, en)))", " #1 $(_vport(bb, c.name)) = 1'b0;")
  end
  _simswitches(out, e, bb, divs, enables)
  for src in unique(c.from for c in bb.tree if c.from !== nothing)
    _simsource(out, e, bb, divs, enables, src)
  end
  for p in bb.ports
    p.dir === :output && println(out, "  assign $(p.vname) = 0;")
  end
  println(out, "endmodule")
  print(io, String(take!(out)))
  nothing
end

simmodel(path::AbstractString, T::Type; kwargs...) =
  open(io -> simmodel(io, T; kwargs...), path, "w")

"""
    simmodels(io, T; scale=NamedTuple())
    simmodels(path, T; scale=NamedTuple())

Write a `simmodel` for every black box in the design `T` that declares a clock
tree, in declaration order and each one once. `scale` is per black box, giving
the clock overrides `simmodel` takes.

```julia
simmodels("standins.v", Top; scale=(PLL = (clk_slow = 4,),))
```
"""
function simmodels(io::IO, T::Type; scale=NamedTuple())
  seen = Set{Type}()
  _simmodels!(io, T, seen, _asscale(scale))
  nothing
end

simmodels(path::AbstractString, T::Type; kwargs...) =
  open(io -> simmodels(io, T; kwargs...), path, "w")

### helpers

_asclockscale(d::Dict{Symbol,Int}) = d
_asclockscale(d::AbstractDict) = Dict{Symbol,Int}(Symbol(k) => Int(v) for (k, v) in d)
_asclockscale(nt::NamedTuple) = Dict{Symbol,Int}(pairs(nt))

# the stand-in's header: the black box's own ports, its clock outputs as regs
function _simdecls(bb::BlackboxDef)
  decls = String[]
  for p in bb.ports
    p.dir === :clock && push!(decls, "input wire $(p.vname)")
    p.dir === :input && push!(decls, _decl("input wire", string(p.vname), p.width; signed=p.signed))
    p.dir === :output && push!(decls, _decl("output wire", string(p.vname), p.width; signed=p.signed))
    p.dir === :clockout && push!(decls, "output reg $(p.vname)")
  end
  decls
end

# every clock the source drives, slowest first so a divided clock settles at the
# same source edge the faster ones do
function _simsource(out, e::Emitter, bb::BlackboxDef, divs, enables, src)
  println(out, "  always @(posedge $(_vport(bb, src))) begin")
  order = sort([i for (i, c) in enumerate(bb.tree) if c.from === src];
               by = i -> -get(divs, bb.tree[i].name, bb.tree[i].divide),
               alg = Base.Sort.MergeSort)
  for i in order
    c = bb.tree[i]
    d = get(divs, c.name, c.divide)
    p = mod(c.phase, d)
    v = _vport(bb, c.name)
    cnt = "n$(i)_$v"
    ind = "    "
    en = get(enables, i, nothing)
    if en !== nothing
      println(out, ind, "if ($(_ref(e, en))) begin")
      ind = "      "
    end
    # a square wave, not a pulse: a design may sample a slow clock as data, and it
    # has to see a settled level between edges
    half = cld(d, 2)
    if d == 1
      println(out, ind, "#1 $v = 1'b1;")
    else
      println(out, ind, "if ($cnt % 32'd$d == 32'd$p) #1 $v = 1'b1;")
      println(out, ind, "else if ($cnt % 32'd$d == 32'd$(mod(p + half, d))) #1 $v = 1'b0;")
      println(out, ind, "$cnt = $cnt + 32'd1;")
    end
    en === nothing || println(out, "    end")
  end
  println(out, "  end\n")
end

# A clock with several sources is a mux, and a change of its selection is not an
# edge: the output takes the level of the source it switches to when that is low,
# and otherwise holds until that source's own next edge. That is the simulator's
# rule too -- it counts the edges of whichever source is selected, and a switch by
# itself never counts -- so the two agree whatever the two sources are doing at
# the moment of the switch. The selected level is a wire of its own, acted on at
# its falling edge, so the enables have settled by the time it is read.
function _simswitches(out, e::Emitter, bb::BlackboxDef, divs, enables)
  for name in unique(c.name for c in bb.tree)
    recipes = [i for (i, c) in enumerate(bb.tree) if c.name === name && c.from !== nothing]
    length(recipes) > 1 || continue
    high = String[]
    for i in recipes
      c = bb.tree[i]
      get(divs, c.name, c.divide) == 1 || continue
      en = get(enables, i, nothing)
      push!(high, en === nothing ? _vport(bb, c.from) : "($(_ref(e, en)) & $(_vport(bb, c.from)))")
    end
    v = _vport(bb, name)
    println(out, "  wire sel_$v = $(isempty(high) ? "1'b0" : join(high, " | "));")
    println(out, "  always @(negedge sel_$v) #1 $v = 1'b0;")
  end
  println(out)
end

_vport(bb::BlackboxDef, name::Symbol) =
  (i = findfirst(p -> p.name === name, bb.ports); i === nothing ? name : bb.ports[i].vname)

# the enable conditions, traced over the part's inputs so they emit as Verilog
function _simenables(e::Emitter, T::Type, bb::BlackboxDef)
  ins = NamedTuple(p.name => Wire{p.width}(:input, Any[]; signed=p.signed, name=p.vname)
                   for p in bb.ports if p.dir === :input)
  out = Dict{Int,Wire}()
  for (i, c) in enumerate(bb.tree)
    c.hasenable || continue
    w = _clockenable(T, Val(i), ins)
    w isa Wire || (w = constant(Bool(w)))
    out[i] = w
  end
  out
end

function _simnodes(enables)
  acc = Dict{Int,Wire}()
  for w in values(enables)
    _collect_nodes!(acc, w)
  end
  acc
end

function _simmodels!(io, T::Type, seen, scale)
  for FT in fieldtypes(T)
    FT <: QuartzModule || continue
    if isblackbox(FT)
      FT in seen && continue
      push!(seen, FT)
      isempty(blackbox(FT).tree) || simmodel(io, FT; scale=get(scale, nameof(FT), Dict{Symbol,Int}()))
    else
      _simmodels!(io, FT, seen, scale)
    end
  end
end
